name: Daily Meme Creator

on:
  schedule:
    - cron: '30 3 * * *'   # 3:30 AM UTC = 9 AM India time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          
      - name: Install tools
        run: |
          pip install pillow requests
        
      - name: Run mega meme bot
        run: python clean_meme_bot.py
        
      - name: Upload memes
        uses: actions/upload-artifact@v6
        with:
          name: my-memes
          path: |
            *.png
            *.json
            *.txt
